#!/bin/bash
php bin/console doctrine:database:drop --if-exists --force
php bin/console doctrine:database:create --if-not-exists
php bin/console doctrine:schema:update --force
cat dump.sql|xargs -0 php bin/console doctrine:query:sql