<?php

namespace AppBundle\Repository;

/**
 * FlatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatsRepository extends \Doctrine\ORM\EntityRepository
{
}
